# Generated by Django 4.2.6 on 2024-01-10 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_book_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='null', max_length=20)),
                ('bookid', models.IntegerField(default=0)),
                ('borrow_date', models.DateField()),
            ],
        ),
    ]
