# Generated by Django 4.2.6 on 2024-01-09 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_borrowrecord'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='borrowrecord',
            table=None,
        ),
    ]
