# Generated by Django 4.2.6 on 2024-01-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_alter_borrowrecord_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrecord',
            name='booktitle',
        ),
        migrations.AddField(
            model_name='borrowrecord',
            name='bookid',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='username',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
