# Generated by Django 4.2.6 on 2024-01-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_remove_borrowrecord_booktitle_borrowrecord_bookid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrecord',
            name='bookid',
            field=models.IntegerField(default=0),
        ),
    ]
